### ISSUE TITLE
Is this going to be maintained?   

### ISSUE THREAD

**Issue by sprynm** [unlight/gulp-extract-media-queries#1]
I'm curious to use this but get a number of compatibility warnings on install.  Do you have plans to maintain/update? 

npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade

npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

npm WARN prefer global js-beautify@1.4.2 should be installed with -g

**Comment by unlight** [comment]
I'm not using this plugin atm, so I do not see this warnings =)
Thanks for the report, I will check and update dependencies.

**Comment by unlight** [comment]
Sorry, but I did not realize that project have no unit tests, I need some time to implement it.

**Comment by unlight** [comment]
@sprynm 
Warnings you mentioned were coming from dependency `clean-up-string`, I updated it from 1.0.0 -> 2.0.0
You should not see any warnings now (version 1.1.0)
